POS ASP.NET MVC/Controllers/BarcodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using POSDataAccess;


namespace POS_ASP.NET_MVC.Controllers
{
    public class BarcodesController : Controller
    {
        private POSDBContext db = new POSDBContext();

        // GET: Barcodes
        public ActionResult Index()
        {
            //var barcodes = db.Barcodes.Include(b => b.Product).OrderBy(x => x.Product.Type).Take(10);
            var barcodes = db.Barcodes.Include(b => b.Product).OrderByDescending(x => x.Date).Skip(1 * 10).Take(10);
            return View(barcodes.ToList());
        }
        [HttpPost]
        //public ActionResult Index(string num)
        //{
        //    int a = 0;
        //    if (num != "")
        //        a = int.Parse(Request["num"]);

        //    var barcodes = db.Barcodes.Include(b => b.Product).OrderBy(x => x.Product.Type).Skip(a * 10).Take(10);

        //    return View(barcodes.ToList());
        //}
        // GET: Barcodes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Barcode barcode = db.Barcodes.Find(id);
            if (barcode == null)
            {
                return HttpNotFound();
            }
            return View(barcode);
        }

        // GET: Barcodes/Create
        public ActionResult Create()
        {
            ViewBag.Product_ID = new SelectList(db.Products, "ID", "Type");
            ViewBag.Barcode_Serial = new SelectList(db.Gifts, "Barcode", "SL");
            return View();
        }

        // POST: Barcodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Barcode_Serial,Product_ID,Color,Date")] Barcode barcode)
        {
            if (ModelState.IsValid)
            {
                db.Barcodes.Add(barcode);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Product_ID = new SelectList(db.Products, "ID", "Type", barcode.Product_ID);
            ViewBag.Barcode_Serial = new SelectList(db.Gifts, "Barcode", "SL", barcode.Barcode_Serial);
            return View(barcode);
        }

        // GET: Barcodes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Barcode barcode = db.Barcodes.Find(id);
            if (barcode == null)
            {
                return HttpNotFound();
            }
            ViewBag.Product_ID = new SelectList(db.Products, "ID", "Type", barcode.Product_ID);
            ViewBag.Barcode_Serial = new SelectList(db.Gifts, "Barcode", "SL", barcode.Barcode_Serial);
            return View(barcode);
        }

        // POST: Barcodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Barcode_Serial,Product_ID,Color,Date")] Barcode barcode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(barcode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Product_ID = new SelectList(db.Products, "ID", "Type", barcode.Product_ID);
            ViewBag.Barcode_Serial = new SelectList(db.Gifts, "Barcode", "SL", barcode.Barcode_Serial);
            return View(barcode);
        }

        // GET: Barcodes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Barcode barcode = db.Barcodes.Find(id);
            if (barcode == null)
            {
                return HttpNotFound();
            }
            return View(barcode);
        }

        // POST: Barcodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Barcode barcode = db.Barcodes.Find(id);
            db.Barcodes.Remove(barcode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

POS ASP.NET MVC/Views/Barcodes/Create.cshtml
@model POSDataAccess.Barcode

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Barcode</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Barcode_Serial, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Barcode_Serial, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Barcode_Serial, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Product_ID, "Product_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Product_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Product_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

POS ASP.NET MVC/Views/Barcodes/Delete.cshtml
@model POSDataAccess.Barcode

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Barcode</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Color)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Color)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Product.Type)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Product.Type)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Gift.SL)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Gift.SL)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

POS ASP.NET MVC/Views/Barcodes/Details.cshtml
@model POSDataAccess.Barcode

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Barcode</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Color)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Color)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Product.Type)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Product.Type)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Gift.SL)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Gift.SL)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Barcode_Serial }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

POS ASP.NET MVC/Views/Barcodes/Edit.cshtml
@model POSDataAccess.Barcode

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Barcode</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Barcode_Serial)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Product_ID, "Product_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Product_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Product_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

POS ASP.NET MVC/Views/Barcodes/Index.cshtml
@model IEnumerable<POSDataAccess.Barcode>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        function decrease() {
            var aa = $('#num').val();
            //alert(aa);
            $('#num').val(--aa);
        }
        function increase() {
            var aa = $('#num').val();
            $('#num').val(++aa);
        }
    </script>
</head>
<body>
    @using (Html.BeginForm("Index", "Barcodes", FormMethod.Post, new { id = "barcodeForm", name = "barcodeForm" }))
    {
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-responsive table-hover table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Barcode_Serial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            
            <th></th>
        </tr>
    
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Type)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Barcode_Serial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Barcode_Serial }) |
                @Html.ActionLink("Details", "Details", new { id = item.Barcode_Serial }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Barcode_Serial })
            </td>
        </tr>
    }
    
    </table>
    @*<input type="submit" onclick="decrease()" value="Previous"/>
    <input type="submit" onclick="increase()" value="Next" />
    <input id="num" type="text" value="1" />*@
    }
</body>
</html>